services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    networks:
      - mynet

  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: debian-dev
    stdin_open: true
    tty: true
    networks:
      - mynet
    volumes:
      - /mnt/wslg:/mnt/wslg
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:0
      - PULSE_SERVER=unix:/mnt/wslg/PulseServer
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir

networks:
  mynet:
